services:
  dmz-gw:
    image: ${PROBE_IMAGE}
    container_name: neobank-dmz-gw
    command: ["sh", "-c", "python -m http.server 80"]
    networks:
      - dmz-net
      - core-net

  corp-agent:
    image: ${PROBE_IMAGE}
    container_name: neobank-corp-agent
    command: ["sh", "-c", "python -m http.server 80"]
    networks:
      - corp-net
      - core-net

  core-svc:
    image: ${PROBE_IMAGE}
    container_name: neobank-core-svc
    command: ["sh", "-c", "python -m http.server 80"]
    networks:
      - core-net
      - pci-net
      - core-db-net

  pci-svc:
    image: ${PROBE_IMAGE}
    container_name: neobank-pci-svc
    command: ["sh", "-c", "python -m http.server 80"]
    networks:
      - pci-net
      - pci-db-net

  core-db:
    image: ${POSTGRES_IMAGE}
    container_name: neobank-core-db
    environment:
      POSTGRES_DB: ${CORE_DB_NAME}
      POSTGRES_USER: ${CORE_DB_USER}
      POSTGRES_PASSWORD: ${CORE_DB_PASSWORD}
    networks:
      - core-db-net
    volumes:
      - core-db-data:/var/lib/postgresql/data
      - ./db/core/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CORE_DB_USER} -d ${CORE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pci-db:
    image: ${POSTGRES_IMAGE}
    container_name: neobank-pci-db
    environment:
      POSTGRES_DB: ${PCI_DB_NAME}
      POSTGRES_USER: ${PCI_DB_USER}
      POSTGRES_PASSWORD: ${PCI_DB_PASSWORD}
    networks:
      - pci-db-net
    volumes:
      - pci-db-data:/var/lib/postgresql/data
      - ./db/pci/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PCI_DB_USER} -d ${PCI_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dmz-net:
    name: ${DMZ_NET}
    driver: bridge

  corp-net:
    name: ${CORP_NET}
    driver: bridge

  core-net:
    name: ${CORE_NET}
    driver: bridge

  pci-net:
    name: ${PCI_NET}
    driver: bridge

  core-db-net:
    name: ${CORE_DB_NET}
    driver: bridge

  pci-db-net:
    name: ${PCI_DB_NET}
    driver: bridge

volumes:
  core-db-data:
  pci-db-data:
